//Voos Domésticos
//Passagens Para O Norte Do Brasil
let NorteBR_Economica = 2500 //Passagens Econômica Sul
let NorteBR_Economica_Kids = 1800 //Passagens Econômica Sul
let NorteBR_Executiva = (NorteBR_Economica+(2500*20)/100) //Passagens Executiva Norte
let NorteBR_Executiva_Kids = (1800+20) //Passagens Executiva Norte

//Passagens Para O Sul Do Brasil
let SulBR_Economica = 3000 //Passagens Econômica Sul
let SulBR_Executiva = 4000 //Passagens Executiva Sul
let SulBR_Economica_Kids = 3000 //Passagens Econômica Sul
let SulBR_Executiva_Kids = 4000 //Passagens Executiva Para Crianças Sul

//Voos Internacionais
//Continente Asiático
let Classe_Economica_Asia = 4600 //Passagens Econômica
let Classe_Executiva_Asia = 6000 //Passagens Executiva

//Continente Europeu
let Classe_Economica_Europa = 5800 //Passagens Econômica
let Classe_Executiva_Europa = 7300 //Passagens Executiva

//Continente Africano
let Classe_Economica_Africa = 4200 //Passagens Econômica
let Classe_Executiva_Africa = 6900 //Passagens Executiva

let Passageiros_Adultos = 34 //Quantidade De Passageiros Adultos
let Passageiros_Kids = 13 //Quantidade de Passageiros Crianças
let Passageiros_Totais = 47 //Quantidade Total De Passageiros

if (NorteBR_Economica / NorteBR_Economica_Kids) {
    console.log(``)
}
