//Voos Domésticos
//Passagens Para O Norte Do Brasil
let NorteBR_Economica = 2500 //Passagens Econômica Sul
let NorteBR_Economica_Kids = 1800 //Passagens Econômica Sul
let NorteBR_Executiva = (NorteBR_Economica+(2500*20)/100) //Passagens Executiva Norte
let NorteBR_Executiva_Kids = (1800+20) //Passagens Executiva Norte

//Passagens Para O Sul Do Brasil
let SulBR_Economica_Todos = 3000 //Passagens Econômica Sul
let SulBR_Executiva_Todos = 4000 //Passagens Executiva Sul

//Voos Internacionais
//Continente Asiático
let Classe_Economica_Asia = 4600 //Passagens Econômica
let Classe_Executiva_Asia = 6000 //Passagens Executiva

//Continente Europeu
let Classe_Economica_Europa = 4600 //Passagens Econômica
let Classe_Executiva_Europa = 6000 //Passagens Executiva

//Continente Africano
let Classe_Economica_Africa = 4600 //Passagens Econômica
let Classe_Executiva_Africa = 6000 //Passagens Executiva

let Passageiros_Adultos = 34 //Quantidade De Passageiros Adultos
let Passageiros_Kids = 13 //Quantidade de Passageiros Crianças
let Passageiros_Totais = 47 //Quantidade Total De Passageiros